export const ACTION_TOGGLE_FILTER = 'TOGGLE_FILTER';

export const FILTER_TYPES = {
  DISTINCTION: 'FILTER_DISTINCTION',
  FIRST_CLASS: 'FILTER_FIRST_CLASS',
  SECOND_CLASS: 'FILTER_SECOND_CLASS',
  FAILED: 'FILTER_FAILED',
};
